export const HOME_LISTINGS_REQUEST = 'HOME_LISTINGS_REQUEST';
export const HOME_LISTINGS_SUCCESS = 'HOME_LISTINGS_SUCCESS';
export const HOME_LISTINGS_FAIL = 'HOME_LISTINGS_FAIL';

export const LISTING_ID_REQUEST = 'LISTING_ID_REQUEST';
export const LISTING_ID_SUCCESS = 'LISTING_ID_SUCCESS';
export const LISTING_ID_FAIL = 'LISTING_ID_FAIL';




